name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '15 6 * * *'

jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show build env info
        run: |
          bash ./scripts/print_info.sh
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --version
        pytest -vv || echo $$
        pytest -v --cov=. --cov-report=html || echo $$
    - uses: actions/upload-artifact@v1
      with:
        name: pytest-results
        path: htmlco
        
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Image build
      run: |
        docker image build -t lookupy .
        docker image ls --all
      
