name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '15 6 * * *'
    - cron: '15 18 * * *'

jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show build env info
        run: |
          bash ./scripts/print_info.sh
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --version
        pytest -vv || echo $$
        pytest -v --cov=. --cov-report=html || echo $$
    - uses: actions/upload-artifact@v1
      name: Upload pytest results
      with:
        name: pytest-results
        path: htmlcov

  docker_image_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Image build
      run: |
        DOCKER_BUILDKIT=1 docker image build -t lookupy:${GITHUB_RUN_ID} .
    - name: Image list show
      run: |
        docker image ls --all
    - name: Image save
      run: |
        docker image save lookupy:${GITHUB_RUN_ID} > lookupy.tar
    - uses: actions/upload-artifact@v1
      name: Upload docker image
      with:
        name: docker-image
        path: lookupy.tar

  exec_triby:
    runs-on: ubuntu-latest
    needs: docker_image_build
    steps:
    - uses: actions/checkout@v2
    - name: Install triby
      run: |
        ./scripts/install_triby.sh
        trivy --version
    - uses: actions/download-artifact@v1
      name: Download docker image
        with:
          name: docker-image
    - name: Check docker image
      run: |
        pwd && ls -l
